name: API linting

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        cd api
        npm install
      env:
        CI: true
    - name: npm run lint
      run: |
        cd api
        npm run lint
      env:
        CI: true
    - name: npm run test
      run: |
        cd api
        npm run test
      env:
        CI: true
